apiVersion: v1
kind: Service
metadata:
  name: tasks-mgt-api-service
spec:
  selector:
    app: tasks-service-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: tasks-port1
      nodePort: 30010
  type: NodePort
