"""empty message

Revision ID: 3026c3d1563c
Revises: 
Create Date: 2023-12-30 08:36:47.904098+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3026c3d1563c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date_clocked_in', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_clocked_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_recorded', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_id'), 'timesheet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_id'), table_name='timesheet')
    op.drop_table('timesheet')
    # ### end Alembic commands ###
