apiVersion: v1
kind: Service
metadata:
  name: timesheets-mgt-api-service
spec:
  selector:
    app: timesheets-service-api
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
      name: timesheet-port1
      nodePort: 30001
  type: NodePort
