apiVersion: v1
kind: Service
metadata:
  name: users-mgt-api-service
spec:
  selector:
    app: users-service-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: tasks-port1
      nodePort: 30011
  type: NodePort
